#!/bin/sh

SEARCH_DEPS=$(find . -type f -name '*.js' | 
  sed \
    -e "/ti.js/d" \
    -e "/underscore.js/d" \
    -e "/webgl.js/d" \
    -e "/titanium_debug.js/d" \
    -e "/titanium_release.js/d" \
    -e "/titanium.js/d"
)

DEPS="ti.js libs/underscore.js util/webgl.js $SEARCH_DEPS"

for i in $DEPS
do
  echo $i
done
